// <auto-generated />
using EF_Core_Exam.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EF_Core_Exam.Migrations
{
    [DbContext(typeof(ClassContext))]
    [Migration("20240319115012_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EF_Core_Exam.Models.MFG", b =>
                {
                    b.Property<long>("mfgid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mfgname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobileno")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("mfgid");

                    b.ToTable("table_mfg");
                });

            modelBuilder.Entity("EF_Core_Exam.Models.autoparts", b =>
                {
                    b.Property<long>("autopartsid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("autopartname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("mfgid")
                        .HasColumnType("bigint");

                    b.Property<string>("partdesc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("autopartsid");

                    b.HasIndex("mfgid");

                    b.ToTable("table_autoparts");
                });

            modelBuilder.Entity("EF_Core_Exam.Models.brand", b =>
                {
                    b.Property<long>("brandid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("brandaddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("brandname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("brandid");

                    b.ToTable("table_brand");
                });

            modelBuilder.Entity("EF_Core_Exam.Models.car", b =>
                {
                    b.Property<long>("carid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("autopartsid")
                        .HasColumnType("bigint");

                    b.Property<long>("brandid")
                        .HasColumnType("bigint");

                    b.Property<decimal>("partprice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("qty")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("carid");

                    b.HasIndex("autopartsid");

                    b.HasIndex("brandid");

                    b.ToTable("table_car");
                });

            modelBuilder.Entity("EF_Core_Exam.Models.autoparts", b =>
                {
                    b.HasOne("EF_Core_Exam.Models.MFG", "MFG")
                        .WithMany("autoparts")
                        .HasForeignKey("mfgid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MFG");
                });

            modelBuilder.Entity("EF_Core_Exam.Models.car", b =>
                {
                    b.HasOne("EF_Core_Exam.Models.autoparts", "autoparts")
                        .WithMany("cars")
                        .HasForeignKey("autopartsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF_Core_Exam.Models.brand", "brand")
                        .WithMany("cars")
                        .HasForeignKey("brandid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("autoparts");

                    b.Navigation("brand");
                });

            modelBuilder.Entity("EF_Core_Exam.Models.MFG", b =>
                {
                    b.Navigation("autoparts");
                });

            modelBuilder.Entity("EF_Core_Exam.Models.autoparts", b =>
                {
                    b.Navigation("cars");
                });

            modelBuilder.Entity("EF_Core_Exam.Models.brand", b =>
                {
                    b.Navigation("cars");
                });
#pragma warning restore 612, 618
        }
    }
}
