// <auto-generated />
using CurdUsingRepoDI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CurdUsingRepoDI.Migrations
{
    [DbContext(typeof(ClassContext))]
    partial class ClassContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CurdUsingRepoDI.Models.Dept", b =>
                {
                    b.Property<long>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DeptId"));

                    b.Property<string>("DeptName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeptId");

                    b.ToTable("Depts");

                    b.HasData(
                        new
                        {
                            DeptId = 1L,
                            DeptName = "Cpmputer"
                        },
                        new
                        {
                            DeptId = 2L,
                            DeptName = "Mechanical"
                        },
                        new
                        {
                            DeptId = 3L,
                            DeptName = "Civil"
                        },
                        new
                        {
                            DeptId = 4L,
                            DeptName = "ENTC"
                        });
                });

            modelBuilder.Entity("CurdUsingRepoDI.Models.Emp", b =>
                {
                    b.Property<long>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EmpId"));

                    b.Property<long>("DeptId")
                        .HasColumnType("bigint");

                    b.Property<string>("EmpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpEmailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpMobileNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EmpSalary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmpId");

                    b.HasIndex("DeptId");

                    b.ToTable("Emps");

                    b.HasData(
                        new
                        {
                            EmpId = 1L,
                            DeptId = 1L,
                            EmpAddress = "Pune",
                            EmpEmailId = "priya@gmail.com",
                            EmpMobileNo = "9876543210",
                            EmpName = "Priyanka",
                            EmpSalary = 9876m
                        },
                        new
                        {
                            EmpId = 2L,
                            DeptId = 2L,
                            EmpAddress = "Pune",
                            EmpEmailId = "sweety@gmail.com",
                            EmpMobileNo = "9999543210",
                            EmpName = "Sweety",
                            EmpSalary = 9777m
                        },
                        new
                        {
                            EmpId = 3L,
                            DeptId = 3L,
                            EmpAddress = "Pune",
                            EmpEmailId = "guddi@gmail.com",
                            EmpMobileNo = "9888543210",
                            EmpName = "Guddi",
                            EmpSalary = 9555m
                        });
                });

            modelBuilder.Entity("CurdUsingRepoDI.Models.Emp", b =>
                {
                    b.HasOne("CurdUsingRepoDI.Models.Dept", "Dept")
                        .WithMany("Emps")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dept");
                });

            modelBuilder.Entity("CurdUsingRepoDI.Models.Dept", b =>
                {
                    b.Navigation("Emps");
                });
#pragma warning restore 612, 618
        }
    }
}
