// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using prachi_exam_core.Models;

namespace prachi_exam_core.Migrations
{
    [DbContext(typeof(ContextClass))]
    [Migration("20240321095001_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("prachi_exam_core.Models.Emp", b =>
                {
                    b.Property<long>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("prachi_exam_core.Models.EmpSalary", b =>
                {
                    b.Property<long>("EmpSalaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("EmpId")
                        .HasColumnType("bigint");

                    b.HasKey("EmpSalaryId");

                    b.HasIndex("EmpId");

                    b.ToTable("EmpSalarys");
                });

            modelBuilder.Entity("prachi_exam_core.Models.SalaryAddition", b =>
                {
                    b.Property<long>("SalaryAdditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AdditionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AdditionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("EmpId")
                        .HasColumnType("bigint");

                    b.HasKey("SalaryAdditionId");

                    b.HasIndex("EmpId");

                    b.ToTable("SalaryAdditions");
                });

            modelBuilder.Entity("prachi_exam_core.Models.SalayDeduction", b =>
                {
                    b.Property<long>("SalaryDeductionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("DeductionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DeductionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("EmpId")
                        .HasColumnType("bigint");

                    b.HasKey("SalaryDeductionId");

                    b.HasIndex("EmpId");

                    b.ToTable("salayDeductions");
                });

            modelBuilder.Entity("prachi_exam_core.Models.EmpSalary", b =>
                {
                    b.HasOne("prachi_exam_core.Models.Emp", "Emp")
                        .WithMany("EmpSalaries")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("prachi_exam_core.Models.SalaryAddition", b =>
                {
                    b.HasOne("prachi_exam_core.Models.Emp", "Emp")
                        .WithMany("SalariesAdditions")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("prachi_exam_core.Models.SalayDeduction", b =>
                {
                    b.HasOne("prachi_exam_core.Models.Emp", "Emp")
                        .WithMany("SalariesDeductions")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("prachi_exam_core.Models.Emp", b =>
                {
                    b.Navigation("EmpSalaries");

                    b.Navigation("SalariesAdditions");

                    b.Navigation("SalariesDeductions");
                });
#pragma warning restore 612, 618
        }
    }
}
